SET IDENTITY_INSERT [dbo].[Gear] ON
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (23, N'Leather Boots', 100, N'Boots', 2, 5, 10)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (26, N'Leather Legs', 100, N'Legs', 2, 5, 10)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (28, N'Leather Shoulders', 100, N'Shoulders', 2, 5, 10)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (30, N'Shinobi Head', 500, N'Head', 15, 50, 70)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (34, N'Leather Belt', 100, N'Belt', 2, 5, 10)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (36, N'Leather Head', 100, N'Head', 2, 5, 10)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (37, N'Shinobi Belt', 500, N'Belt', 10, 30, 50)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (38, N'Shinobi Chest', 300, N'Chest', 5, 20, 30)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (39, N'Shinobi Shoulders', 500, N'Shoulders', 15, 40, 60)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (41, N'Shinobi Boots', 500, N'Boots', 15, 40, 60)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (42, N'Leather Chest', 100, N'Chest', 2, 15, 8)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (43, N'Dragon Ninja Chest', 1500, N'Chest', -20, 160, 300)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (44, N'Dragon Ninja Boots', 1500, N'Boots', -15, 120, 200)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (45, N'Dragon Ninja Legs', 1500, N'Legs', -25, 190, 300)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (46, N'Dragon Ninja Head', 1500, N'Head', -15, 200, 270)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (47, N'Dragon Ninja Belt', 1200, N'Belt', -15, 180, 220)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (48, N'Dragon Ninja Shoulders', 1200, N'Shoulders', -25, 230, 280)
INSERT INTO [dbo].[Gear] ([Id], [Name], [Price], [Category], [Intelligence], [Strength], [Agility]) VALUES (49, N'Shinobu Legs', 300, N'Legs', 15, 50, 60)
SET IDENTITY_INSERT [dbo].[Gear] OFF
